#!/bin/bash

BIN=/cygdrive/d/ProgFile/Toolkits/SublimeText/sublime_text.exe

if [ $# -eq 0 ] ; then 
	"$BIN" &
	exit $?
fi

for file ; do
	[ ! -e $file ] && { echo "$file not exsited!"; continue; }

	f=`cygpath -aw "$file"`
	"$BIN" "$f" &

	echo "$file opened!"
done
